[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.33"
auto_detect_solc = false
evm_version = "osaka"
optimizer = true
via_ir = true
optimizer_runs = 10000

auto_detect_remappings = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solady/=lib/solady/src",
    "@risc0-ethereum/=lib/risc0-ethereum/contracts/src/",
    "@elliptic-curve-solidity/=lib/elliptic-curve-solidity/",
]

cbor_metadata = false
bytecode_hash = "none"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
